// 格里昂 APP 戰隊 2026 世界盃 排班資料
// 來源：2026世界盃 排班用 - 格里昂 - 工作表1.csv
// 範圍：2026/6/1 ~ 2026/7/31 (61 天)
//
// 班別代碼：
//   M    = 早班 (Morning)，例 8-10 或 8-9
//   N    = 晚班 (Night) 23-8
//   H    = 假日加班 (Holiday overtime) 9-14
//   off  = 休假

export type ShiftCode = "M" | "N" | "H" | "off"

export interface StaffShifts {
  name: string
  code: string
  shifts: ShiftCode[] // 61 cells，對應 DATES
}

export interface TeamSchedule {
  team: "iOS" | "Android"
  members: StaffShifts[]
}

// 6/1 ~ 7/31 共 61 天
export const DATES = [
  "6/1",
  "6/2",
  "6/3",
  "6/4",
  "6/5",
  "6/6",
  "6/7",
  "6/8",
  "6/9",
  "6/10",
  "6/11",
  "6/12",
  "6/13",
  "6/14",
  "6/15",
  "6/16",
  "6/17",
  "6/18",
  "6/19",
  "6/20",
  "6/21",
  "6/22",
  "6/23",
  "6/24",
  "6/25",
  "6/26",
  "6/27",
  "6/28",
  "6/29",
  "6/30",
  "7/1",
  "7/2",
  "7/3",
  "7/4",
  "7/5",
  "7/6",
  "7/7",
  "7/8",
  "7/9",
  "7/10",
  "7/11",
  "7/12",
  "7/13",
  "7/14",
  "7/15",
  "7/16",
  "7/17",
  "7/18",
  "7/19",
  "7/20",
  "7/21",
  "7/22",
  "7/23",
  "7/24",
  "7/25",
  "7/26",
  "7/27",
  "7/28",
  "7/29",
  "7/30",
  "7/31",
] as const

export const WEEKDAYS = [
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "日",
  "一",
  "二",
  "三",
  "四",
  "五",
] as const

export const TEAMS: TeamSchedule[] = [
  {
    team: "iOS",
    members: [
      {
        name: "Wesley",
        code: "501",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Jeff",
        code: "817",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Finn",
        code: "513",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Lester",
        code: "507",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Jackie",
        code: "857",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "H",
          "H",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "H",
          "H",
          "M",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "off",
          "M",
        ],
      },
    ],
  },
  {
    team: "Android",
    members: [
      {
        name: "Jeremy",
        code: "514",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "N",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Lumos",
        code: "516",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Kent",
        code: "515",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Angela",
        code: "818",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "off",
          "off",
          "off",
          "N",
          "N",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "N",
          "N",
          "N",
          "off",
          "M",
          "N",
          "N",
          "off",
          "off",
          "N",
          "N",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Ronin",
        code: "505",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Schawn",
        code: "504",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
      {
        name: "Pong",
        code: "503",
        shifts: [
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
          "off",
          "off",
          "M",
          "M",
          "M",
          "M",
          "M",
        ],
      },
    ],
  },
]

// 開幕到冠軍戰的重點賽事
// 來源：2025/12/5 華盛頓抽籤後的正式賽程（FIFA + Wikipedia 交叉比對）
// 時間：全部換算成「台北時區」(UTC+8)；美東時間 (EDT, UTC-4) + 12 小時 = 台北
//   例：6/11 15:00 ET 開幕戰 → 6/12 03:00 Taipei
export interface HeadlineMatch {
  date: string // "6/12" 之類（台北日期）
  time: string // "03:00"（台北時間）
  title: string // 顯示用
  stage?: string // 副標：組別 / 場地 / 階段
  wide?: boolean // 在 grid 佔滿一整列（冠軍戰用，避免最後一排空格）
}

export const HEADLINE_MATCHES: HeadlineMatch[] = [
  // ─── 開幕（阿茲特克球場，墨西哥城）
  {
    date: "6/12",
    time: "03:00",
    title: "🇲🇽 墨西哥 vs 🇿🇦 南非",
    stage: "A 組 · 開幕戰 · Estadio Azteca",
  },
  // ─── 主辦三國全亮相
  {
    date: "6/13",
    time: "03:00",
    title: "🇨🇦 加拿大 vs 🇧🇦 波士尼亞",
    stage: "B 組 · BMO Field 多倫多",
  },
  {
    date: "6/13",
    time: "09:00",
    title: "🇺🇸 美國 vs 🇵🇾 巴拉圭",
    stage: "D 組 · SoFi Stadium 洛杉磯",
  },
  // ─── 強權登場
  {
    date: "6/14",
    time: "06:00",
    title: "🇧🇷 巴西 vs 🇲🇦 摩洛哥",
    stage: "C 組",
  },
  {
    date: "6/15",
    time: "04:00",
    title: "🇳🇱 荷蘭 vs 🇯🇵 日本",
    stage: "F 組 · 亞洲視角必看",
  },
  {
    date: "6/16",
    time: "00:00",
    title: "🇪🇸 西班牙 vs 🇨🇻 維德角",
    stage: "H 組 · 賽前排名第一",
  },
  {
    date: "6/17",
    time: "03:00",
    title: "🇫🇷 法國 vs 🇸🇳 塞內加爾",
    stage: "I 組",
  },
  {
    date: "6/17",
    time: "09:00",
    title: "🇦🇷 阿根廷 vs 🇩🇿 阿爾及利亞",
    stage: "J 組 · 衛冕冠軍出戰",
  },
  {
    date: "6/18",
    time: "01:00",
    title: "🇵🇹 葡萄牙 vs 🇨🇩 民主剛果",
    stage: "K 組",
  },
  {
    date: "6/18",
    time: "04:00",
    title: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 英格蘭 vs 🇭🇷 克羅埃西亞",
    stage: "L 組 · 卡達世盃復刻",
  },
  // ─── 主辦三國第二輪
  {
    date: "6/19",
    time: "09:00",
    title: "🇲🇽 墨西哥 vs 🇰🇷 南韓",
    stage: "A 組 第 2 輪",
  },
  {
    date: "6/20",
    time: "03:00",
    title: "🇺🇸 美國 vs 🇦🇺 澳洲",
    stage: "D 組 第 2 輪",
  },
  // ─── 淘汰賽（FIFA 公佈時刻表）
  {
    date: "6/29",
    time: "03:00",
    title: "🔥 R32 開戰",
    stage: "首場 32 強 · SoFi 洛杉磯",
  },
  {
    date: "7/5",
    time: "01:00",
    title: "🎯 R16 開戰",
    stage: "16 強進 8 · NRG 休斯頓",
  },
  {
    date: "7/10",
    time: "05:00",
    title: "QF1 · 八強首戰",
    stage: "Gillette Stadium 波士頓郊區",
  },
  {
    date: "7/15",
    time: "03:00",
    title: "SF1 · 準決賽",
    stage: "AT&T Stadium 達拉斯",
  },
  {
    date: "7/16",
    time: "04:00",
    title: "SF2 · 準決賽",
    stage: "Mercedes-Benz 亞特蘭大",
  },
  {
    date: "7/19",
    time: "06:00",
    title: "🥉 季軍戰",
    stage: "Hard Rock Stadium 邁阿密",
  },
  {
    date: "7/20",
    time: "04:00",
    title: "🏆 冠軍戰",
    stage: "FINAL · MetLife 紐澤西 — Vegas Lights ON",
    wide: true,
  },
]
